### ISSUE TITLE
I find your demo is based on bootrap2,not 3.

### ISSUE THREAD

**Issue by zltqzj** [Vegetam/BootstrapPageGenerator#1]
maybe you haven't finished it?

**Comment by Vegetam** [comment]
Hello Miss Chalk,
Is not yet finished i have added some new functionalities missed in
bootstrap 2 :

http://www.francescomalagrino.com/BootstrapPageGenerator/3/

I have added under components List group and Panels while in this one is
missing :

http://www.francescomalagrino.com/BootstrapPageGenerator/2/

Im basing on the website LayoutIT anyway i'm seeing that are missing other
components that i will add ASAP :)

Many thanks and best regards

2014-02-08 8:43 GMT+01:00 miss_chalk notifications@github.com:

**Comment by zltqzj** [comment]
I look forward to updating it on github by u ,I like layoutit very much .but it doesn't have the version by bootstrap3,what a pity!

I'm not good at using the bootstrap3 ,so I want to learn from your demo.thanks.

**Comment by Vegetam** [comment]
I have added new functionalities :) Next week will try to add more functionalities and something that is working with bootstrap 2 syntax i will made it in bootstrap 3
