### ISSUE TITLE
Grid style error in the generated code

### ISSUE THREAD

**Issue by RDCH106** [Vegetam/BootstrapPageGenerator#17]
When a new grid is added, the generated code has horizontal scrolling.

**Comment by RDCH106** [comment]
Solved with [Hot Fix](https://github.com/Vegetam/BootstrapPageGenerator/pull/15/commits/fcfb223d3dc685928b6a9140714f56140ea1ff00).

Searching better solution...

Example grid show the following code:

```
<div class="row-fluid">
    <div class="span12">            
    </div>
</div>
```

But adding de 12 grid, the code is the following one:

```
<div class="row-fluid">
    <div class="col-xs-12">
    </div>
</div>
```

I appreciate some help to understand it.

**Comment by Vegetam** [comment]
Hi sorry I did understand is solved with an Hot fix is correct?

**Comment by RDCH106** [comment]
Yes, I solved it in [this commit](https://github.com/Vegetam/BootstrapPageGenerator/pull/15/commits/5d47672286be4f4308cfc8c67bb078b898079232).

The fix solves the problem, but it would be good a deeper revision.
