### ISSUE TITLE
add new grid

### ISSUE THREAD

**Issue by babyss69** [Vegetam/BootstrapPageGenerator#18]
Hello ,
when I try to make personalized grid, it does not work.

example: 2 2 2 2 2 2

**Comment by Vegetam** [comment]
Hi, If you try this piece of code works :

```
   <div class="lyrow ui-draggable">
                <a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i>Remove</a> <span class="drag label"><i class="icon-move"></i>Drag</span>
                <div class="preview">
                  <input value="2 2 2 2 2 2" type="text">
                </div>
                <div class="view">
                  <div class="row-fluid clearfix">
                    <div class="col-xs-2 column"></div>
                    <div class="col-xs-2 column"></div>
                    <div class="col-xs-2 column"></div>
                    <div class="col-xs-2 column"></div>
                    <div class="col-xs-2 column"></div>
                    <div class="col-xs-2 column"></div>
                  </div>
                </div>
              </div>
```

**Comment by babyss69** [comment]
Hi ,

thanks you.

Best regards

---

De : Francesco Malagrino notifications@github.com
Envoyé : mardi 11 octobre 2016 09:48
À : Vegetam/BootstrapPageGenerator
Cc : babyss69; Author
Objet : Re: [Vegetam/BootstrapPageGenerator] add new grid (#18)

Hi, If you try this piece of code works :

   <div class="lyrow ui-draggable">
                <a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i>Remove</a> <span class="drag label"><i class="icon-move"></i>Drag</span>
                <div class="preview">
                  <input value="2 2 2 2 2 2" type="text">
                </div>
                <div class="view">
                  <div class="row-fluid clearfix">
                    <div class="col-xs-2 column"></div>
                    <div class="col-xs-2 column"></div>
                    <div class="col-xs-2 column"></div>
                    <div class="col-xs-2 column"></div>
                    <div class="col-xs-2 column"></div>
                    <div class="col-xs-2 column"></div>
                  </div>
                </div>
              </div>

##

**Comment by Vegetam** [comment]
No problem at all

Best regards
