### ISSUE TITLE
Can you make a version based entirely on bootstrap 3?

### ISSUE THREAD

**Issue by xbzhs** [Vegetam/BootstrapPageGenerator#2]
hello vegetam!
  your tool is very good.but I found that all components in your tool are based on bootstrap 2,except list group and panels.Can you make a version based entirely on bootstrap 3? I need it, thank you very much!

**Comment by Vegetam** [comment]
Heya I'm working on this, because i noticed that LayoutIT is not using
really bootstrap3 but just added this 2 new functionalities.

I will updated something hope this weekend :)

2014-02-10 4:28 GMT+01:00 小硕 notifications@github.com:

**Comment by Vegetam** [comment]
Hi ,

I fixed the layout that was a messed for some strange reason.

Can you please check?

I will add some more new content Next week or from 2 weeks.

 Many thanks and best regards

2014-02-10 4:28 GMT+01:00 小硕 notifications@github.com:

**Comment by Vegetam** [comment]
Hello I made, Some new functionalities,

I will next week try to make everything for bootstrap 3

Many thanks and best regards

2014-02-18 10:09 GMT+01:00 Francesco Malagrinò <
francesco.malagrino@gmail.com>:

**Comment by dsc785** [comment]
Hi, I have looked into your latest update today. works great so far. didn't encounter any issues to report. waiting for your code update next week

Thanks a lot for the effort

**Comment by dalareo** [comment]
Hello, how could we include a "save" button to automatically save the prototype into the server where the Page Generator is hosted (just as Layoutit has beside download button)?
Thanks for your great job!!

**Comment by Vegetam** [comment]
HI David,

How are you?

For that i guess you need use or a function in PHP or any server language
(Java, C# Python etc) or using node.js.

And need be i guess configuration with a DB that will save every prototype.

Glade if my answer can be of any help.

Many thanks and best regards

2014-05-12 2:16 GMT+02:00 David A. Lareo notifications@github.com:

**Comment by akito12** [comment]
hello vegetam!
This tool is good. I want to use BootstrapPageGenerator for other system, but I cannot find the license. What is the license?

**Comment by Vegetam** [comment]
Hi Akito,

its free

You can use it whenever you want :)

Many thanks and best regards

Francesco Malagrino

2015-12-16 4:15 GMT+00:00 Akito UCHIYAMA notifications@github.com:

> hello vegetam!
> This tool is good. I want to use BootstrapPageGenerator for other system,
> but I cannot find the license. What is the license?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Vegetam/BootstrapPageGenerator/issues/2#issuecomment-164988329
> .

## 

Francesco Malagrino
Alfresco Consulting
mobile: +44 (0)7701-285269
http://university.alfresco.com/ACE  http://university.alfresco.com/ACA

**Comment by DoDSoftware** [comment]
Two years later and still not updated to bootstrap 3, why even have this up anymore?

**Comment by Vegetam** [comment]
It is on boostrap 3.

The only thing that I can't touch are the columns that are based on
boostrap 2 but that is only the layout.

All the other application is on Bootstrap 3.

2016-02-03 18:47 GMT+00:00 Wesley Smith notifications@github.com:

> Two years later and still not updated to bootstrap 3, why even have this
> up anymore?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Vegetam/BootstrapPageGenerator/issues/2#issuecomment-179399830
> .

## 

Francesco Malagrino
Alfresco Consulting
mobile: +44 (0)7701-285269
http://university.alfresco.com/ACE  http://university.alfresco.com/ACA

**Comment by Vegetam** [comment]
I created a new version just right now.

this is without anymore the span column that you could use in the version 2.5

Many thanks and best regards

Vegetam

**Comment by DoDSoftware** [comment]
Ah, I see. I just saw all the span4 and saw that both of these issues were still open. Nice job!

**Comment by DoDSoftware** [comment]
New look is also much cleaner ;)
