### ISSUE TITLE
⚠️ Authors section in README

### ISSUE THREAD

**Issue by RDCH106** [Vegetam/BootstrapPageGenerator#22]
I do not understand why the name of the section is Author**S** and it is only one author. It would be better change de name of the section to Author (singular) or eliminate the section. In the [Constributors section](https://github.com/Vegetam/BootstrapPageGenerator/graphs/contributors) of the repository it is possible to see the authors.

Another topic is the reason because the other authors of the section were deleted:

* https://github.com/Vegetam/BootstrapPageGenerator/commit/d9592e2e9352e2b0755fc148b4120b7045f7faaa

I am not ungry for me. I am ungry because your develop it is strongly based on the work of [justjavac](https://github.com/justjavac?tab=repositories) in [LayoutIt](https://github.com/justjavac/layoutit) project. Please keep the references because you based your work in that project. The project it is not genuine  work of you and you do not inspired by the justjavac's work to code from the begining the code of your porject. You have used code from LayoutIt project directly.

**Please keep the acknowledgment of all its authors and do not get it for yourself only!**

**Comment by Vegetam** [comment]
Not really they copy by mine and improved it something but then I modify it again check their code and mine and you can see several bugs like the UL, LI some alignment and so on.
The color to them doesn't work. Plus they just make 1 commit and put as the author when other contributors commit more on this project and they didn't either ask to put their name in the readme.




I created it by version 2.5 till version 4 alpha and I'm the only one that most of the time modify it

They are not Author but contributor that is kinda different from the author.

In fact, there is another project where I commit only myself based on Version 4 alpha and will be soon another one based on version 4 beta 2.

**Comment by RDCH106** [comment]
> Not really they copy by mine and improved it something but then I modify it again check their code and mine and you can see several bugs like the UL, LI some alignment and so on.

Yes! It is reasonable. All the software has improvements, but the architecture of the base comes from where you know, even if you do not recognize it. 😫

> The color to them doesn't work. Plus they just make 1 commit and put as the author when other contributors commit more on this project and they didn't either ask to put their name in the readme.

Administrate it if you consider that you are the main author (by README) and the maintainer. I remember that I have contributed with many PR:

* https://github.com/Vegetam/BootstrapPageGenerator/pulls?q=is%3Apr+author%3ARDCH106+is%3Aclosed

I proposed the possibility to run online the project using raw-code, the integration with codacy...

You can do two options add the authors even they did not ask for that because in all cases the appears in the contributors section, or remove the section. The problem is that you have deleted the authors that appeared in the README and you only keep your name. It is very polite on your part! 🙄

> I created it by version 2.5 till version 4 alpha and I'm the only one that most of the time modify it.

I do not discuss this argument, you have right! But being the mayor contributor it is not reason to delete other authors. The problem is put only your name. Everyone know that the project is yours, is in the URL of the repository:

> Vegetam/BootstrapPageGenerator

Acknowledgment for other authors is desired if you explicitly put your name in the README.

> They are not Author but contributor that is kinda different from the author.

Be carefull!! Contributors are authors of the project too. Because without their code the project doesn't work exactly in the same way. A contributor is an author that start works in the project when the base of the project is coded. In any case I will never make the difference between author and contributors, for me are the same. You can think in main author for the original idea or main changes, in mantainer for the person that makes the neccesary changes to assure the project working... All contributors are authors but all the authors do not have the same weight in the project, it could be depend in quality of the code, the number of code lines, the support, the documentation...

**If you treat in this way the contributions of the people who contribute in an altruistic way, the people will not want to contribute in your project!**

**Comment by RDCH106** [comment]
> In fact, there is another project where I commit only myself based on Version 4 alpha and will be soon another one based on version 4 beta 2.

I do not understand the reason because you open new repsoitory... :

* https://github.com/Vegetam/BoostrapPageGenerator4

If it is another version continue with the original repository. I think that it is the perfect way to remove the commit history, using your old repository as base.

**Comment by Vegetam** [comment]
Its because this is on version 3 since version 4 was in alpha and now in beta 2 still not sure when will be available the stable version 4 of Bootstrap. 

Oh okay than I will re-add them as author / contributor didn't knew that but now I got it :)

**Comment by RDCH106** [comment]
@Vegetam Thanks!

Open Source is for add efforts and not subtract them. All the contributions add for the total of the project.

Because many of us do not do it for money, at least give the acknowledgement. It is not too much and it makes the people be happy. ☺️

**Comment by Vegetam** [comment]
I put everybody that commits please check the readme let me know if I miss somebody and there was a misunderstanding from Author and contributor but yeah I add everybody

I will put you guys also on the Bootstrap 4 branch because anyway is based on this one with some changes :)

This weekend btw I will put also inside that the Bootstap 4 beta 2 :) playing on it at the moment and checking if I broke something from the version alpha

**Comment by Vegetam** [comment]
No problem guys :) let me know if I can do anything else :)

**Comment by Vegetam** [comment]
I will close the issue and yeah always good have an help and contributors / author :)

**Comment by RDCH106** [comment]
Good! 👍

I think that justjavac should be added, not as Contributor/Author, but orignal idea author. You say that the project is an alternative to justjavac's project and you used hisr project as base (using also the code). Esentialy your project is a fork focused in improve the legacy of LayoutIt.

Proposal:

### Authors

  * [Vegetam](https://github.com/Vegetam) (Main Author)
  * [justjavac](https://github.com/justjavac) (Original idea & Code base)
  
  A special thanks as author and contributor also to :
  
  * [RDCH106](https://github.com/RDCH106) (Contributor / Author)
  * [Phil](https://github.com/QuakePhil) (Contributor / Author)
  * [yaneq](https://github.com/yaneq) (Contributor / Author)
  * [legnaleama](https://github.com/legnaleama) (Contributor / Author)
