### ISSUE TITLE
Container missing in new layout and padding top incorrect in developer and preview mode

### ISSUE THREAD

**Issue by DoDSoftware** [Vegetam/BootstrapPageGenerator#8]
In the new layout, there is no div with the tag "content" in the top left corner as was in the previous version. Additionally, when viewing the layout in developer or preview mode , the top padding is removed making the content fall behind the top navbar which may be related to the first issue. 

![image](https://cloud.githubusercontent.com/assets/8271955/12806034/ee01c990-cac7-11e5-9bc0-c5db8a66bbff.png)
![image](https://cloud.githubusercontent.com/assets/8271955/12806037/0174c482-cac8-11e5-80e0-f78d7b46f477.png)

**Comment by Vegetam** [comment]
Hi,

thanks for report me this issue.

I fixed it.

Can you try again ?

Many thanks and best regards

Francesco Malagrino

2016-02-04 4:49 GMT+00:00 Wesley Smith notifications@github.com:

> In the new layout, there is no div with the tag "content" in the top left
> corner as was in the previous version. Additionally, when viewing the
> layout in developer or preview mode , the top padding is removed making the
> content fall behind the top navbar which may be related to the first issue.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/8271955/12806034/ee01c990-cac7-11e5-9bc0-c5db8a66bbff.png
> [image: image]
> https://cloud.githubusercontent.com/assets/8271955/12806037/0174c482-cac8-11e5-80e0-f78d7b46f477.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Vegetam/BootstrapPageGenerator/issues/8.

## 

Francesco Malagrino
Alfresco Consulting
mobile: +44 (0)7701-285269
http://university.alfresco.com/ACE  http://university.alfresco.com/ACA
