### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ridethemonkey** [Vegetam/BootstrapPageGenerator#9]
What is the license of this tool? It looks like justjavac/layoutit may infringe the copyright of layoutit.com - and by implication therefore so does this project. Do you know whether this is the case, or was  justjavac/layoutit created independently of LayoutIt?

Having said that, I've looked through the code of your project and you've achieved some fantastic development here, well done.

**Comment by Vegetam** [comment]
Hi ,

the code is similar but note the same.

I create myself and you can use it whenever you want :)

Many thanks and best regards

Francesco Malagrino

2016-03-19 7:58 GMT+00:00 ridethemonkey notifications@github.com:

> What is the license of this tool? It looks like justjavac/layoutit may
> infringe the copyright of layoutit.com - and by implication therefore so
> does this project. Do you know whether this is the case, or was
> justjavac/layoutit created independently of LayoutIt?
> 
> Having said that, I've looked through the code of your project and you've
> achieved some fantastic development here, well done.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Vegetam/BootstrapPageGenerator/issues/9

## 

Francesco Malagrino
Alfresco Consulting
mobile: +44 (0)7701-285269
http://university.alfresco.com/ACE  http://university.alfresco.com/ACA

**Comment by RDCH106** [comment]
It is important the software licensing.

Reading your comments, the best option for you is  [GNU Affero](https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License) or if you are not agree with [FSF](https://es.wikipedia.org/wiki/Free_Software_Foundation) an alternative could be [MIT License](https://en.wikipedia.org/wiki/MIT_License).

**Comment by RDCH106** [comment]
License Added:

2ff7745d0395142522d7f4605acf04bf3faf4e1b

The issue must be closed.
